// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKJSmUh7U5rivkjJTEnnu8eBNUAixNrz4',
    appId: '1:602901731854:web:ab0f6977e02b23b8fdfa5f',
    messagingSenderId: '602901731854',
    projectId: 'studytrack-b1f67',
    authDomain: 'studytrack-b1f67.firebaseapp.com',
    storageBucket: 'studytrack-b1f67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8V3409azQ9cXP3BR_wEoSQAtu9CbE8j8',
    appId: '1:602901731854:android:150a03fc8b31ba2efdfa5f',
    messagingSenderId: '602901731854',
    projectId: 'studytrack-b1f67',
    storageBucket: 'studytrack-b1f67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwUvwX658jLCLamzfcjp3ey6S05qi6dZ8',
    appId: '1:602901731854:ios:a42b6b3c94cca760fdfa5f',
    messagingSenderId: '602901731854',
    projectId: 'studytrack-b1f67',
    storageBucket: 'studytrack-b1f67.firebasestorage.app',
    iosBundleId: 'cl.Pereira.STUDYTRACK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwUvwX658jLCLamzfcjp3ey6S05qi6dZ8',
    appId: '1:602901731854:ios:838102178c0587fcfdfa5f',
    messagingSenderId: '602901731854',
    projectId: 'studytrack-b1f67',
    storageBucket: 'studytrack-b1f67.firebasestorage.app',
    iosBundleId: 'com.example.studytrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKJSmUh7U5rivkjJTEnnu8eBNUAixNrz4',
    appId: '1:602901731854:web:95b11f4d5c9ad7e0fdfa5f',
    messagingSenderId: '602901731854',
    projectId: 'studytrack-b1f67',
    authDomain: 'studytrack-b1f67.firebaseapp.com',
    storageBucket: 'studytrack-b1f67.firebasestorage.app',
  );
}
